/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export { ActivationError } from './models/ActivationError';
export type { ActivationMethod } from './models/ActivationMethod';
export type { ActivationRequest } from './models/ActivationRequest';
export type { ActivationResponse } from './models/ActivationResponse';
export type { Address } from './models/Address';
export type { AllLicensedProductsResponse } from './models/AllLicensedProductsResponse';
export type { AllResourcesResponse } from './models/AllResourcesResponse';
export type { ApplicationToken } from './models/ApplicationToken';
export type { AuthTokenResponse } from './models/AuthTokenResponse';
export type { Category } from './models/Category';
export type { CategoryResponse } from './models/CategoryResponse';
export type { CompleteChangelogResult } from './models/CompleteChangelogResult';
export type { ConfigurationResponse } from './models/ConfigurationResponse';
export type { Country } from './models/Country';
export type { Credentials } from './models/Credentials';
export type { DownloadArtifact } from './models/DownloadArtifact';
export type { DownloadArtifactType } from './models/DownloadArtifactType';
export type { DownloadFile } from './models/DownloadFile';
export type { DownloadFileType } from './models/DownloadFileType';
export type { DownloadHardwarePlatform } from './models/DownloadHardwarePlatform';
export type { DownloadPlatform } from './models/DownloadPlatform';
export type { DownloadProductsResponse } from './models/DownloadProductsResponse';
export type { DownloadProductsResponseLegacy } from './models/DownloadProductsResponseLegacy';
export type { DownloadTargetDir } from './models/DownloadTargetDir';
export { DownloadUnavailableProduct } from './models/DownloadUnavailableProduct';
export type { Enduser } from './models/Enduser';
export { Error } from './models/Error';
export type { ErrorResponse } from './models/ErrorResponse';
export { GetUsersMeResponse } from './models/GetUsersMeResponse';
export type { Language } from './models/Language';
export type { License } from './models/License';
export type { LicensedProductObject } from './models/LicensedProductObject';
export type { LicensedProductsResponse } from './models/LicensedProductsResponse';
export type { LicensesResponse } from './models/LicensesResponse';
export type { LicenseTransferRequest } from './models/LicenseTransferRequest';
export type { LicenseTransferResponse } from './models/LicenseTransferResponse';
export type { MyProductsResponse } from './models/MyProductsResponse';
export type { MySubscriptionsResponse } from './models/MySubscriptionsResponse';
export type { NativeIDResponse } from './models/NativeIDResponse';
export type { OAuth2TokenAuth0 } from './models/OAuth2TokenAuth0';
export type { OAuth2TokenSDBS } from './models/OAuth2TokenSDBS';
export type { Product } from './models/Product';
export type { ProductBasicData } from './models/ProductBasicData';
export type { ProductByUpidResponse } from './models/ProductByUpidResponse';
export type { ProductDifferencesItem } from './models/ProductDifferencesItem';
export type { ProductDifferencesResponse } from './models/ProductDifferencesResponse';
export type { ProductResponse } from './models/ProductResponse';
export type { ProductResponseObject } from './models/ProductResponseObject';
export type { ProductUpgradePath } from './models/ProductUpgradePath';
export type { ProductUpgradePathItem } from './models/ProductUpgradePathItem';
export type { ProductUpgradePathsResponse } from './models/ProductUpgradePathsResponse';
export type { ProductWithResource } from './models/ProductWithResource';
export { RAS3HardwareProfile } from './models/RAS3HardwareProfile';
export type { RAS3Header } from './models/RAS3Header';
export type { RAS3TokenPayload } from './models/RAS3TokenPayload';
export type { RegisterProductRequest } from './models/RegisterProductRequest';
export type { RegisterProductResponse } from './models/RegisterProductResponse';
export type { RegistrationsResponse } from './models/RegistrationsResponse';
export type { Resource } from './models/Resource';
export type { ResponseHead } from './models/ResponseHead';
export type { ResponseHeadWithErrors } from './models/ResponseHeadWithErrors';
export type { SerialNumberExportsResponse } from './models/SerialNumberExportsResponse';
export type { SignUpResponse } from './models/SignUpResponse';
export type { SingleResourceResponse } from './models/SingleResourceResponse';
export type { SubscribedLicensedProduct } from './models/SubscribedLicensedProduct';
export type { SubscribedProduct } from './models/SubscribedProduct';
export { Subscription } from './models/Subscription';
export type { SubscriptionBundle } from './models/SubscriptionBundle';
export type { SubscriptionBundleResponse } from './models/SubscriptionBundleResponse';
export type { SubscriptionCancellationReasons } from './models/SubscriptionCancellationReasons';
export { SubscriptionCancellationStatus } from './models/SubscriptionCancellationStatus';
export type { SubscriptionCreation } from './models/SubscriptionCreation';
export type { SubscriptionExtensionItem } from './models/SubscriptionExtensionItem';
export { SubscriptionInToken } from './models/SubscriptionInToken';
export type { SubscriptionInvoice } from './models/SubscriptionInvoice';
export type { SubscriptionPage } from './models/SubscriptionPage';
export { SubscriptionPageCreation } from './models/SubscriptionPageCreation';
export type { SubscriptionPricePoint } from './models/SubscriptionPricePoint';
export type { SubscriptionPricePoints } from './models/SubscriptionPricePoints';
export type { SubscriptionProduct } from './models/SubscriptionProduct';
export type { SubscriptionProducts } from './models/SubscriptionProducts';
export { SubscriptionStatus } from './models/SubscriptionStatus';
export type { SubscriptionUserInfo } from './models/SubscriptionUserInfo';
export type { Token } from './models/Token';
export type { UserSignup } from './models/UserSignup';
export type { UsersMeInputMessage } from './models/UsersMeInputMessage';
export type { UsersMeResponse } from './models/UsersMeResponse';

export { ActivationsService } from './services/ActivationsService';
export { AuthService } from './services/AuthService';
export { BaseService } from './services/BaseService';
export { ChangelogsService } from './services/ChangelogsService';
export { ConfigurationsService } from './services/ConfigurationsService';
export { DownloadService } from './services/DownloadService';
export { LicenseTransferService } from './services/LicenseTransferService';
export { ProductsService } from './services/ProductsService';
export { ResourcesService } from './services/ResourcesService';
export { SerialNumbersService } from './services/SerialNumbersService';
export { SubscriptionsService } from './services/SubscriptionsService';
export { SupportersService } from './services/SupportersService';
export { UsersService } from './services/UsersService';
